server:
verbosity: 4
interface: 0.0.0.0
port: 53
# Activar DNS-over-TLS
tls-service-key: "/etc/unbound/key.pem"
tls-service-pem: "/etc/unbound/cert.pem"
interface: 0.0.0.0@853
chroot: ""
do-ip4: yes
do-udp: yes
do-tcp: yes
access-control: 0.0.0.0/0 allow
# Validación de DNSSEC
auto-trust-anchor-file: "/etc/unbound/root.key"
val-log-level: 3
harden-dnssec-stripped: yes
harden-referral-path: yes
module-config: "validator iterator"
root-hints: "/etc/unbound/root.hints"
use-syslog: no
log-servfail: yes     # Esto es clave para ver por qué algo falla
log-queries: yes
local-zone: "test." nodefault

trust-anchor: "example.test. 3600 IN DNSKEY 257 3 13 ugmOZXQl8b4SgWxEdC2RMrrMDzcF34/3uocWI1v/iEptYc3Zy+h63m3xFFFTyM7/dr/H6Wl4gzxKr5cpDbUe3Q=="

# Reenvio a servidores publicos para lo que no sea example.test.
forward-zone:
name: "."
forward-addr: 1.1.1.1     # Cloudflare
forward-addr: 8.8.8.8     # Google

# Zona stub para preguntar a tu servidor autoritativo Knot
stub-zone:
  name: "example.test."
  stub-addr: 172.20.0.2@53  # La IP y puerto del contenedor de Knot